#' @title cfp_run_map
#'
#' @description An S3 class for run maps generated by a call to \link{run_map}() to
#' be used in alternate(). Either create a new run map from a cfp_pfres or
#' cfp_fgres model or extract an existing run_map from an cfp_altres object.
#'
#' @param x An object from which to extract a run_map.
#'
#' @param ... Additional arguments to form a valid cfp_run_map object.
#'
#' @export
cfp_run_map <- function(x,
                        ...){
  UseMethod("cfp_run_map")
}

# extract only

#' @exportS3Method
cfp_run_map.cfp_altres <- function(x,
                                   ...){
  out <- attr(x, "run_map")
  out
}

# helper ----

#' @exportS3Method
cfp_run_map.cfp_pfres <- cfp_run_map.cfp_fgres <-
  function(x,
           ...){

  x <-
    new_cfp_run_map(x,
                    id_cols,
                    params,
                    method,
                    type,
                    n_runs,
                    layers_different,
                    layers_from,
                    layers_altmap,
                    runmap_type,
                    params_df
    )
  x <- validate_cfp_run_map(x)
  x
}


# creator -------------

new_cfp_run_map <- function(x,
                            id_cols,
                            params,
                            method,
                            type,
                            n_runs,
                            layers_different,
                            layers_from,
                            layers_altmap,
                            runmap_type,
                            params_df
){

  stopifnot(is.data.frame(x))

  x <- structure(x,
                 class = c("cfp_run_map",class(x)[!grepl("cfp_run_map",class(x))]),
                 params = params,
                 method = method,
                 type = type,
                 n_runs = n_runs,
                 layers_different = layers_different,
                 layers_from = layers_from,
                 layers_altmap = layers_altmap,
                 runmap_type = runmap_type,
                 params_df = params_df)
 x
}


# validator -----------

validate_cfp_run_map <- function(x){

  stopifnot(inherits(x, "cfp_run_map"))
  stopifnot(is.data.frame(x))

  stopifnot("run_id" %in% names(x))
  x
}



###############
### HELPERS ### -----------------
###############

# extractors ---------
#' @describeIn extractors runmap_type
#' @export
cfp_runmap_type <- function(x){
  UseMethod("cfp_runmap_type")
}

#' @exportS3Method
cfp_runmap_type.cfp_run_map <- function(x){
  attr(x, "runmap_type")
}


#' @describeIn extractors params_df
#' @export
cfp_params_df <- function(x){
  UseMethod("cfp_params_df")
}

#' @exportS3Method
cfp_params_df.cfp_run_map <- function(x){
  attr(x, "params_df")
}



#' @describeIn extractors n_runs
#' @export
cfp_n_runs <- function(x){
  UseMethod("cfp_n_runs")
}

#' @exportS3Method
cfp_n_runs.cfp_run_map <- function(x){
  attr(x, "n_runs")
}

#' @describeIn extractors layers_different
#' @export
cfp_layers_different <- function(x){
  UseMethod("cfp_layers_different")
}

#' @exportS3Method
cfp_layers_different.cfp_run_map <- function(x){
  attr(x, "layers_different")
}

#' @describeIn extractors layers_from
#' @export
cfp_layers_from <- function(x){
  UseMethod("cfp_layers_from")
}

#' @exportS3Method
cfp_layers_from.cfp_run_map <- function(x){
  attr(x, "layers_from")
}
#' @describeIn extractors layers_altmap
#' @export
cfp_layers_altmap <- function(x){
  UseMethod("cfp_layers_altmap")
}

#' @exportS3Method
cfp_layers_altmap.cfp_run_map <- function(x){
  attr(x, "layers_altmap")
}




###### PRINTING #######
#' @exportS3Method
print.cfp_run_map <- function(x, ...){
  n <- cfp_n_runs(x)

  cat("\nA cfp_run_map to be used in alternate(). \n")
  cat("number of runs: ", n,"\n")
  cat("parameters to alternate:\n")
  print(cfp_params_df(x))
  NextMethod()
}






