#' @title cfp_run_map
#'
#' @description An S3 class for run maps generated by a call to run_map() to
#' be used in alternate(). Either create a new run map from a cfp_pfres or
#' cfp_fgres model or extract an existing run_map from an cfp_altres object.
#'
#' @inherit run_map
#'
#'
#' @export
cfp_run_map <- function(x,
                        ...){
  UseMethod("cfp_run_map")
}

# extract only

#' @exportS3Method
cfp_run_map.cfp_altres <- function(x,
                                   ...){
  out <- attr(x, "run_map")
  out
}

# helper ----

#' @exportS3Method
cfp_run_map.cfp_pfres <- cfp_run_map.cfp_fgres <-
  function(x,
           ...){

  x <-
    new_cfp_run_map(x,
                    id_cols,
                    params,
                    method,
                    type,
                    n_runs,
                    layers_different,
                    runmap_type,
                    params_df
    )
  x <- validate_cfp_run_map(x)
  x
}


# creator -------------

new_cfp_run_map <- function(x,
                            id_cols,
                            params,
                            method,
                            type,
                            n_runs,
                            layers_different,
                            runmap_type,
                            params_df
){

  stopifnot(is.data.frame(x))

  x <- structure(x,
                 class = c("cfp_run_map",class(x)[!grepl("cfp_run_map",class(x))]),
                 params = params,
                 method = method,
                 type = type,
                 n_runs = n_runs,
                 layers_different = layers_different,
                 runmap_type = runmap_type,
                 params_df = params_df)
 x
}


# validator -----------

validate_cfp_run_map <- function(x){

  stopifnot(inherits(x, "cfp_run_map"))
  stopifnot(is.data.frame(x))

  stopifnot("run_id" %in% names(x))
  x
}



###############
### HELPERS ### -----------------
###############

# extractors ---------
#' @export
cfp_runmap_type <- function(x){
  UseMethod("cfp_runmap_type")
}

#' @exportS3Method
cfp_runmap_type.cfp_run_map <- function(x){
  attr(x, "runmap_type")
}


#' @export
cfp_params_df <- function(x){
  UseMethod("cfp_params_df")
}

#' @exportS3Method
cfp_params_df.cfp_run_map <- function(x){
  attr(x, "params_df")
}


#' @export
cfp_n_runs <- function(x){
  UseMethod("cfp_n_runs")
}

#' @exportS3Method
cfp_n_runs.cfp_run_map <- function(x){
  attr(x, "n_runs")
}






###### PRINTING #######
#' @exportS3Method
print.cfp_run_map <- function(x, ...){
  n <- cfp_n_runs(x)

  cat("\nA cfp_run_map to be used in alternate(). \n")
  cat("number of runs: ", n,"\n")
  cat("parameters to alternate:\n")
  print(cfp_params_df(x))
  NextMethod()
}






