#' @title cfp_run_map
#'
#' @description An S3 class for run maps generated by a call to run_map() to
#' be used in alternate().
#'
#' @inherit run_map
#'
#' @export

# helper --------------

cfp_run_map <- function(x,
                        id_cols,
                        params,
                        method,
                        type,
                        n_runs,
                        layers_different){

  x <-
  new_cfp_run_map(x,
                  id_cols,
                  params,
                  method,
                  type,
                  n_runs,
                  layers_different
  )

  x <- validate_cfp_run_map(x)
  x
}


# creator -------------

new_cfp_run_map <- function(x,
                            id_cols,
                            params,
                            method,
                            type,
                            n_runs,
                            layers_different
){

  stopifnot(is.data.frame(x))

  x <- structure(x,
                 class = c("cfp_run_map",class(x)),
                 params = params,
                 method = method,
                 type = type,
                 n_runs = n_runs,
                 layers_different = layers_different)
 x
}


# validator -----------

validate_cfp_run_map <- function(x){

  stopifnot(inherits(x, "cfp_run_map"))
  stopifnot(is.data.frame(x))

  stopifnot("run_id" %in% names(x))
  x
}



