#' @title cfp_pfres
#'
#'@description A function to create an object of class cfp_pfres. This is the
#' central result class generated by running \code{pro_flux()}. Intended for
#' internal use only.
#'
#' @param x A valid \code{cfp_mod} object
#' @param y The corresponding PROFULX \code{data.frame}.
#'
#'
#'

cfp_pfres <- function(x,y){

  stopifnot(inherits(x,"cfp_pfmod"))
  x$PROFLUX <- y

  structure(x,
            class = c("cfp_pfres",class(x)))
  x <- validate_cfp_pfres(x)
  x
}

validate_cfp_pfres <- function(x){

  select_cols <- c("sp_id", "step_id")

  PF <- x$PROFLUX %>% dplyr::left_join(x$profiles)
  stopifnot("PROFLUX and soilphys must have the same structure!" =
              dplyr::all_equal(PF[,select_cols] %>% dplyr::distinct(),
                               x$soilphys[,select_cols]
                               ))
  x
}
