#' @title PFres
#'
#' @description This is the central S3 class generated by pro_flux() that
#' stores all the additional function arguments used in the pro_flux()
#' function call, except for \code{gasdata} \code{soilphys} and \code{known_flux}.
#'
#' It behaves just like a data.frame but stores additional information
#' in the attributes. This enables the extraction of additional information
#' such as efflux and also helps keeping track of different models, similar
#' to the \code{lm} class.



#' @export

new_PFres <- function(tbl = list(),
                      layers_map = list(),
                      id_cols = character(),
                      storage_term = logical(),
                      zero_flux = logical(),
                      zero_limits = numeric(),
                      known_flux_factor = numeric(),
                      Ds_optim = logical(),
                      evenness_factor = numeric()
                      ){

  stopifnot(is.list(tbl))

  structure(tbl,
            class = c("PFres","data.frame"),
            layers_map = layers_map,
            id_cols = id_cols,
            storage_term = storage_term,
            zero_flux = zero_flux,
            zero_limits = zero_limits,
            known_flux_factor = known_flux_factor,
            Ds_optim = Ds_optim,
            evenness_factor = evenness_factor

            )
  }


#' @export


PFres <- function(tbl,
                  layers_map,
                  id_cols,
                  storage_term,
                  zero_flux,
                  zero_limits,
                  known_flux_factor,
                  Ds_optim,
                  evenness_factor
                  ) {

  tbl <- new_PFres(tbl,
                   layers_map,
                   id_cols,
                   storage_term,
                   zero_limits,
                   known_flux_factor,
                   Ds_optim,
                   evenness_factor
                   )
}

##### EXTRACTOR FUNCTIONS #####

id_cols <- function(x){
  attr(x,"id_cols")
}



