#' @title PFres
#'
#' @description This is the central S3 class generated by pro_flux() that
#' stores all the additional function arguments used in the pro_flux()
#' function call, except for \code{gasdata} \code{soilphys} and \code{known_flux}.
#'
#' It behaves just like a data.frame but stores additional information
#' in the attributes. This enables the extraction of additional information
#' such as efflux and also helps keeping track of different models, similar
#' to the \code{lm} class.
#'
#' @inheritParams pro_flux
#'
#' @export

new_PFres <- function(tbl = list(),
                      layers_map = list(),
                      id_cols = character(),
                      storage_term = logical(),
                      zero_flux = logical(),
                      zero_limits = numeric(),
                      known_flux = list(),
                      known_flux_factor = numeric(),
                      DSD0_optim = logical(),
                      evenness_factor = numeric(),
                      gasdata = list(),
                      profiles = list()
                      ){

  stopifnot(is.list(tbl))

  structure(tbl,
            class = c("PFres","data.frame"),
            layers_map = layers_map,
            id_cols = id_cols,
            storage_term = storage_term,
            zero_flux = zero_flux,
            zero_limits = zero_limits,
            known_flux = known_flux,
            known_flux_factor = known_flux_factor,
            DSD0_optim = DSD0_optim,
            evenness_factor = evenness_factor,
            gasdata = gasdata,
            profiles = profiles

            )
  }


#' @export


PFres <- function(tbl,
                  layers_map,
                  id_cols,
                  storage_term,
                  zero_flux,
                  zero_limits,
                  known_flux,
                  known_flux_factor,
                  DSD0_optim,
                  evenness_factor,
                  gasdata,
                  profiles
                  ) {

  tbl <- new_PFres(tbl,
                   layers_map,
                   id_cols,
                   storage_term,
                   zero_flux,
                   zero_limits,
                   known_flux,
                   known_flux_factor,
                   DSD0_optim,
                   evenness_factor,
                   gasdata,
                   profiles
                   )
}

##### EXTRACTOR FUNCTIONS #####

PF_id_cols <- function(x){
  attr(x,"id_cols")
}
PF_gasdata <- function(x){
  attr(x,"gasdata")
}
PF_layers_map <- function(x){
  attr(x,"layers_map")
}
PF_storage_term <- function(x){
  attr(x,"storage_term")
}
PF_known_flux <- function(x){
  attr(x,"known_flux")
}
PF_known_flux_factor <- function(x){
  attr(x,"known_flux_factor")
}
PF_zero_flux <- function(x){
  attr(x,"zero_flux")
}
PF_evenness_factor <- function(x){
  attr(x,"evenness_factor")
}
PF_profiles <- function(x){
  attr(x,"profiles")
}
