#' @title PFres
#'
#' @description This is the central S3 class generated by pro_flux() that
#' stores all the additional function arguments used in the pro_flux()
#' function call, except for \code{gasdata} \code{soilphys} and \code{known_flux}.
#'
#' It behaves just like a data.frame but stores additional information
#' in the attributes. This enables the extraction of additional information
#' such as efflux and also helps keeping track of different models, similar
#' to the \code{lm} class.
#'
#' @inheritParams pro_flux
#' @name PFres
#'
#' @export
NULL



#' @rdname PFres
# helper
PFres <- function(tbl,
                  layers_map,
                  id_cols,
                  storage_term,
                  zero_flux,
                  zero_limits,
                  known_flux,
                  known_flux_factor,
                  DSD0_optim,
                  evenness_factor,
                  gasdata,
                  profiles
                  ) {

  x <- new_PFres(tbl,
                   layers_map,
                   id_cols,
                   storage_term,
                   zero_flux,
                   zero_limits,
                   known_flux,
                   known_flux_factor,
                   DSD0_optim,
                   evenness_factor,
                   gasdata,
                   profiles
                   )

  validate_PFres(x)
}

#'
# constructor
new_PFres <- function(tbl = list(),
                      layers_map = list(),
                      id_cols = character(),
                      storage_term = logical(),
                      zero_flux = logical(),
                      zero_limits = numeric(),
                      known_flux = list(),
                      known_flux_factor = numeric(),
                      DSD0_optim = logical(),
                      evenness_factor = numeric(),
                      gasdata = list(),
                      profiles = list()
){

  stopifnot(is.list(tbl))
  stopifnot(is.list(layers_map))
  stopifnot(is.logical(zero_flux))
  stopifnot(is.numeric(zero_limits))
  stopifnot(is.na(known_flux) | is.list(known_flux))
  stopifnot(is.logical(DSD0_optim))
  stopifnot(is.numeric(evenness_factor))
  stopifnot(is.list(gasdata))
  stopifnot(is.list(gasdata))

  structure(tbl,
            class = c("PFres","data.frame"),
            layers_map = layers_map,
            id_cols = id_cols,
            storage_term = storage_term,
            zero_flux = zero_flux,
            zero_limits = zero_limits,
            known_flux = known_flux,
            known_flux_factor = known_flux_factor,
            DSD0_optim = DSD0_optim,
            evenness_factor = evenness_factor,
            gasdata = gasdata,
            profiles = profiles

  )
}

# validator

validate_PFres <- function(x){

  stopifnot(inherits(x,"PFres"))

  # get arguments to env
  obj_names <- names(attributes(new_PFres()))
  obj_names <- obj_names[-which(obj_names == "class")]

  l <- sapply(obj_names, function(n) {
    attr(x, n)
  }, USE.NAMES = T)

  list2env(l, environment())

  gasdata <- pf_gasdata(x)

  # check that there are no unexpected attributes
  attr_names <- names(attributes(x))
  attr_names <- attr_names[-which(attr_names %in%
                                    names(attributes(data.frame())))
                           ]

  if (!all(attr_names %in% obj_names)){
    stop("unexpected attributes")
  }

  # check if all prof_ids are present for all parameters
  prof_ids <- profiles %>% dplyr::pull(prof_id)
  if (!length(prof_ids) == length(unique(prof_ids))){
    stop("prof_id in profiles not unique")
  }

  tbl_ids <- x$prof_id %>% unique()
  if (!all(tbl_ids %in% prof_ids)){
    stop("object has prof_ids not present in profiles")
  }

  gd_ids <- gasdata$prof_id %>% unique()
  if (!all(gd_ids %in% prof_ids)){
    stop("gasdata has prof_ids not present in profiles")
  }

  # check that range of upper/ lower agree based on layers_map
  id_lmap <- id_cols[id_cols %in% names(layers_map)]
  id_lmap <- ifelse(length(id_lmap) == 0,
                    character(),
                    id_lmap)

  drange <-
  layers_map %>%
    dplyr::group_by(dplyr::across(dplyr::any_of(id_lmap))) %>%
    dplyr::summarise(umax = max(upper),
                     lmin = min(lower))


  id_x <- id_lmap[id_lmap %in% names(x)]
  x_depths_valid <-
  drange %>%
    dplyr::right_join(x %>% dplyr::select(!dplyr::any_of(c("umax","lmin"))),
                      by = id_x) %>%
    dplyr::mutate(valid_row = (upper > lmin & lower < umax)) %>%
    dplyr::pull(valid_row) %>%
    all()

  x_depths_valid <- ifelse(length(x_depths_valid) == 0,
                           FALSE,
                           x_depths_valid)

  if (!x_depths_valid){
    stop("range of upper/ lower outside of layers_map")
  }

  id_gd <- id_lmap[id_lmap %in% names(gasdata)]

  gd_depths_valid <-
    gasdata %>%
    dplyr::left_join(drange, by = id_gd) %>%
    dplyr::mutate(valid_row = (depth >= lmin & depth <= umax)) %>%
    dplyr::pull(valid_row) %>%
    all()

  if (!gd_depths_valid){
    stop("gasdata depth range outside of layers_map")
  }

  # check for upper/ lower consistency

  if (!is_ul_consistent(x,id_cols[id_cols %in% names(x)])){
    stop("object must be upper / lower consistent.")
  }

  x
}

##### EXTRACTOR FUNCTIONS #####

#' @rdname PFres
pf_soilphys <- function(x){
  x %>%
    dplyr::select(!dplyr::any_of(extracols_pf()))
}

#' @rdname PFres
pf_id_cols <- function(x){
  UseMethod("pf_id_cols")
}
#' @export
pf_id_cols.default <- function(x){
  attr(x,"id_cols")
}



#' @rdname PFres
pf_gasdata <- function(x){
  gd <- attr(x,"gasdata")
  gd %>%
    dplyr::left_join(pf_profiles(x)) %>%
    dplyr::select(!prof_id)
}
#' @rdname PFres
pf_layers_map <- function(x){
  attr(x,"layers_map")
}
#' @rdname PFres
pf_storage_term <- function(x){
  attr(x,"storage_term")
}
#' @rdname PFres
pf_known_flux <- function(x){
  attr(x,"known_flux")
}
#' @rdname PFres
pf_known_flux_factor <- function(x){
  attr(x,"known_flux_factor")
}
#' @rdname PFres
pf_zero_flux <- function(x){
  attr(x,"zero_flux")
}
#' @rdname PFres
pf_evenness_factor <- function(x){
  attr(x,"evenness_factor")
}
#' @rdname PFres
pf_profiles <- function(x){
  attr(x,"profiles")
}

##### Methods #####





