# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cumsumcpp <- function(x) {
    .Call('_ConFluxPro_cumsumcpp', PACKAGE = 'ConFluxPro', x)
}

prod_mod_cpp <- function(prod, height, DS, Fnull, Cnull) {
    .Call('_ConFluxPro_prod_mod_cpp', PACKAGE = 'ConFluxPro', prod, height, DS, Fnull, Cnull)
}

